---
title: "Course syllabus"
subtitle: "Data Science Concepts and Analysis"
---

## Summer 2023 information

### Course staff and roles

-   Instructor: Laura Baracaldo [[email](mailto:lnbaracaldol@ucsb.edu)]

-   Teaching assistants: Doris Padilla [[email](mailto:dorispadilla@ucsb.edu)] and Erika McPhillips [[email](mailto:elm00@pstat.ucsb.edu)].

The instructor is primarily responsible for delivering lectures and course administration. The teaching assistants are primarily responsible for providing lab instruction and managing assessments and course pages. All staff hold regular office hours on a weekly basis open to all enrolled students.

### Meetings

#### Class Meetings: In Summer 2023, lectures are offered in Person, MTWR 2:00pm - 3:05pm ILP 1101.

#### Sections:

-   TR 11:00am - 11:50am, HSSB 1232 (Doris)
-   TR 12:30pm - 1:20pm, HSSB 1215 (Erika)
-   TR 10:00am - 10:50am, HSSB 1232 (Erika)

#### Office Hours:

-   Laura Baracaldo: Old Gym 1201. W 12:00-1:15pm, or via [zoom](https://ucsb.zoom.us/j/87126271060?pwd=cTN2TDh4WEdGWUtRRjY4aWFsUEZ1QT09)

## Content and Materials

Data Science Concepts and Analysis (PSTAT100) is a hands-on introduction to data science intended for intermediate-level students from any discipline with some exposure to probability and basic computing skills, but few or no upper-division courses in statistics or computer science. The course introduces central concepts in statistics -- such as sampling variation, uncertainty, and inference -- in an applied setting together with techniques for data exploration and analysis. Course activities model standard data science workflow practices by example, and successful students acquire programming skills, project management skills, and subject exposure that will serve them well in upper-division courses as well as in independent research or projects.

### Learning outcomes

Successful students will establish foundational data science skills: critical assessment of data quality and sampling design; inspection and tidying of raw data; exploratory, descriptive, visual, and inferential analysis; and interpretation and communication of results for a general audience.

These skills will be discussed in depth during course lectures; students will practice them through lab activities, homework assignments, and project work.

### UCSB catalog listing

### Description

Overview of data science key concepts and the use of tools for data retrieval, analysis, visualization, and reproducible research. Topics include an introduction to inference and prediction, principles of measurement, missing data, and notions of causality, statistical "traps", and concepts in data ethics and privacy. Case studies will illustrate the importance of domain knowledge.

### Prerequisites

-   Probability and Statistics I (PSTAT 120A)

-   Linear Algebra (MATH 4A)

-   Prior experience with Python or another programming language (CMPSC 9 or CMPSC 16). Credit units: 4.

### Readings

Readings for the course will draw on multiple sources, including:

-   [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/);

-   [Berkeley's Data 100 course notes](http://www.textbook.ds100.org/intro.html);

-   collected journal articles distributed as assigned.

### Software

Computing will be hosted at [pstat100.lsit.ucsb.edu](https://pstat100.lsit.ucsb.edu).

Students are encouraged to install software needed to open, edit, and run notebooks on their own machine, in particular:

-   [a Python install](https://www.python.org/downloads/);

-   (recommended) [Miniconda](https://docs.conda.io/en/latest/miniconda.html);

-   [Jupyter](https://jupyter.org/install);

-   packages utilized in course materials (primarily numpy, pandas, altair, and scikit-learn).

Managing package installations will require some (straightforward) use of the package installer `pip` or `pip3` in the command line to retrieve/install packages from the Python Package Index repository. Documentation for specific packages (or a Google search) will indicate the appropriate `pip` command.

## Assessments

Attainment of course learning outcomes will be measured by assessment of submitted work. Submitted work falls into four categories:

-   **Labs** will be assigned weekly in most weeks. These are structured coding assignments with small exercises throughout that introduce the programming skills needed to complete homework assignments.

-   **Homeworks** will be assigned weekly. These are fairly involved assignments which apply concepts and techniques from the lectures and programming skills from the labs to real data sets in order to reproduce an analysis and answer substantive questions. Collaboration is encouraged, and group submissions will be allowed for groups of up to 3 students.

-   **Mini projects** These assignments prompt students to use skills from the course in an unstructured setting to answer high-level questions pertaining to one or more datasets. Mini projects should be completed individually, but discussion is permitted and encouraged.

-   A **course project** will be assigned requiring students to carry out an open-ended data analysis. This will be completed in teams.

Overall scores in the course will be calculated for each student as the weighted average of scores on all submitted work; the relative weighting and letter grade assignments will depend entirely on the score distribution of the class as a whole and as such reflect each student's performance relative to their peers.

## Topics and corresponding assignmets:

The schedule is subject to change based on the progress of the class.

-   Data science life cycle: Lab0

-   Tidy data: Lab1

-   Sampling and bias: Lab2, Hw1

-   Statistical graphics: Lab 3, Mini Project

-   Kernel density estimation: Lab 4, Homework 2.

-   Principal components: Lab 5

-   Simple regression: Hw3

-   Multiple regression: Lab 6

-   Case study and developing 'presentables': Final Project

## Policies

### Communication

There are two primary means of communication outside of scheduled class meetings: office hours and Nectir

#### Email

Course staff have *limited* availability via email. Course staff will make every effort to respond to individual communication within 48 weekday-hours on the following (or similar) matters:

-   accommodations/extensions due to personal circumstances;

-   logistical issues such as access to materials or missing scores;

-   general advising.

*Email should **not** be used to ask content questions or submit assignments (unless specifically requested)*. Emails related to the following (or similar) matters may not receive replies and should be redirected:

-   Troubleshooting codes: Nectir

-   Checking answers: OH or Nectir

-   Clarifying assignment content: OH or Nectir

-   Assignment submission: Gradescope

-   Re-evaluation request: Gradescope

### Expected time commitment

The course is 4 credit units; each credit unit corresponds to an approximate time commitment of 3 hours. So, students should expect to allocate 12 hours per week to the course on average. Course staff are available to help any students spending considerably more time on the class balance the workload.

### Scores and grades

Scores on submitted work can be monitored on Gradescope to ensure fair assignment of course grades. On any individual assignment, re-evaluation can be requested within one week of receiving a score. Requests for re-evaluation made beyond one week after publication of scores may or may not be considered on a discretionary basis.

Determination of letter grade assignments is made entirely at the discretion of the instructor based on the assessments outlined above and consistent with university policy. Students are not permitted to negotiate their grades, and are discouraged from requesting audits, recalculations, or verification of self-calculations after the course has concluded. The instructor is under no obligation to share the details of grade calculations with students or to respond to such requests.

If at the end of the course a student believes their grade was unfairly assigned, either due to discrimination or without basis in coursework, they are entitled to contest it according to the procedure [outlined here](https://my.sa.ucsb.edu/catalog/Current/AcademicPoliciesProcedures/ContestedGrades.aspx).

### Conduct

Students are expected to uphold the [student code of conduct](http://studentconduct.sa.ucsb.edu/policies-procedures) and to maintain integrity. All individually-submitted work must be an honest reflection of individual effort. Evidence of dishonest conduct will be discussed with the student(s) involved and reported to the Office of Student Conduct (OSC). Depending on the nature of the evidence and the violation, penalty in the course may range from a warning to loss of credit to automatic failure. For a definition and examples of dishonesty, a discussion of what constitutes an appropriate response from faculty, and an explanation of the reporting and investigation process, see the [OSC page on academic integrity](https://studentconduct.sa.ucsb.edu/academic-integrity).

### Deadlines and late work

There is a one-hour grace period on all submission deadlines. Late work will not be accepted beyond this.

### Accommodations

Reasonable accommodations will be made for any student with a qualifying disability. Such requests should be made through the Disabled Students Program (DSP). More information, instructions on how to access accommodations, and information on related resources can be found on [the DSP website](https://dsp.sa.ucsb.edu/).

### Feedback

Toward the end of the term students will be given an opportunity to provide feedback about the course via ESCI. In addition, content-specific feedback will be collected for the Central Coast Data Science Partnership (CCDSP) at the end of the quarter. This information will be used to assess learning outcomes, understand student demographics, and plan further course development; input on the CCDSP survey is especially valuable, and a small amount of course credit will be offered for completion of this survey.
