---
title: "Materials"
---

## Getting started Checklist

-   Confirm access to all course pages
-   Read syllabus

## Week 1

*Readings*:

-   [The Data Science Lifecycle](https://learningds.org/ch/01/lifecycle_intro.html)
-   [Understanding data types in python](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)
-   [The basics of numpy arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)
-   [Aggregations: min, max, and everything in between](https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html)

**Tuesday:** [[slides](/docs/Lectures/week0-lifecycle/week0-lifecycle.slides.html)]\
**Lab section:** Lab 0 [zip](/docs/Lab0.zip)\
**Wednesday-Thursday**[[slides](/docs/Lectures/week1-tidy/week1-tidy.slides.html)]\
**Lab section:** Lab 1 [[zip](/docs/Labs/Lab1.zip)][[html](/docs/Labs/Lab1/lab1-pandas.html)]\


## Week 2

*Readings*:

- LDS2.2 [Population, frame, sample](https://learningds.org/ch/02/data_scope_construct.html#)
- Van Buuren, Flexible Imputation of Missing Data, section 2.2 [Concepts in incomplete data](https://stefvanbuuren.name/fimd/sec-idconcepts.html)
- PDSH3.4 [Handling missing data](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html)

**Monday-Thursday**[[slides pdf](/docs/Lectures/week2-sampling/week2 slides.pdf)]\
**Hw1** [[zip](/docs/Hws/Hw1/Hw1.zip)], [[html](/docs/Hws/Hw1/hw1-brfss.html)], due on Tuesday 07/11.\
**Lab2**[[html](/docs/Labs/Lab2/lab2-sampling.html)], [[zip](/docs/Labs/Lab2/lab2-sampling.zip)], due on Thursday 07/13.


## Week 3:

*Readings*:

- Wilke, [Fundamentals of Data Visualization Ch. 2-5](https://clauswilke.com/dataviz/)
- [Choosing scale to reveal structure](https://learningds.org/ch/11/viz_scale.html)
- (Recommended) Cook, D., Lee, E. K., & Majumder, M. (2016). Data visualization and statistical graphics in big data analysis. Annual Review of Statistics and Its Application, 3, 133-159. [[link to paper](https://www.annualreviews.org/doi/full/10.1146/annurev-statistics-041715-033420)]
- (Recommended) Gelman, A., & Unwin, A. (2013). Infovis and statistical graphics: different goals, different looks. Journal of Computational and Graphical Statistics, 22(1), 2-28. [[link to paper](https://www.tandfonline.com/doi/full/10.1080/10618600.2012.761137)]


**Monday-Tuesday**[[slides pdf](/docs/Lectures/week3_visualization/week3-PDFslides.pdf)]\
**Wednesday-Thursday**[[slides](/docs/Lectures/week4-smoothing/lec4PDF_updated.pdf)]\
**Lab3**[[html](/docs/Labs/Lab3/lab3-visualization.html)], [[zip](/docs/Labs/Lab3/lab3-visualization.zip)], due on Monday 07/17.\
**Mini-Project1** [[zip](/docs/Projects/MP1/MP1.zip)], [[html](/docs/Projects/MP1/mp1-airquality.html)], due on Thursday 07/20.\


## Week 4:

*Readings*:

- [Exploratory data analysis](https://learningds.org/ch/10/eda_distributions.html)
- [Principal Component Analysis](https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html)


**Monday-Thursday**[[slides pdf](/docs/Lectures/week5-pca/week5-pca slides.pdf)]\
**Lab4** [[html](/docs/Labs/Lab4/lab4-smoothing.html)], [[zip](/docs/Labs/Lab4/Lab4.zip)], due on Monday 07/24.\
**Hw2** [[zip](/docs/Hws/Hw2/Hw2.zip)], [[html](/docs/Hws/Hw2/hw2-seda.html)], due on Thursday 07/27.\


## Week 5:

*Readings*:

- [Simple linear models](https://learningds.org/ch/15/linear_intro.html)
- [Basics of prediction intervals](https://learningds.org/ch/17/inf_pred_gen_PI.html)
- [Multiple regression](https://learningds.org/ch/15/linear_multi.html)


**Monday-Thursday**[[slides 1](/docs/Lectures/week7-lse.qmd)][[slides 2](/docs/Lectures/week7-slr.qmd)]\
**Lab5** [[html](/docs/Labs/Lab5/lab5-pca.html)], [[zip](/docs/Labs/Lab5/Lab5.zip)], due on Monday 07/31.\
**Hw3** [[zip](/docs/Hws/Hw3/Hw3.zip)], [[html](/docs/Hws/Hw3/hw3-diatom.html)], due on Thursday 08/03.\
**Class Project**[[zip](/docs/Projects/CP/CP.zip)], [[html](/docs/Projects/CP/project-guidelines.html)],[Groups spreadsheet](https://docs.google.com/spreadsheets/d/141QFwC7RxXOSzKzJYl6D0zlc9pFQYYObQTvhAfeqdQ8/edit?usp=sharing) due on Saturday 08/05.\
